kristijanhusak/laravel-form-builder

- README.md
Using a string inside the wrapper option causes an exception on line [171](https://github.com/kristijanhusak/laravel-form-builder/blob/laravel-4/src/Kris/LaravelFormBuilder/FormHelper.php#L171) on FormHelper due to it using an array and not a string.
> Readme suggestion causes exception

- src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
Some other packages register the same `Form` or `Html` aliases, but use
different identifiers for the class within the IOC. This commit adds a
check for whether there is already an existing facade aliased so it does
not overwrite them
> Don't override existing aliases for Form and Html

- src/Kris/LaravelFormBuilder/Form.php
- src/helpers.php
- tests/FormTest.php
Added form_until helper that renders all previously unrendered form fields up until and including the field name passed as the second argument.  E.g.:
```
{!! form_start($form) !!}
{!! form_until($form, 'field_name') !!}
<p>Some other html before continuing with the form...</p>
{!! form_end($form) !!}
```
> Added form_until helper

- src/Kris/LaravelFormBuilder/Form.php
I saw #55 after searching for issues and PR's to do with `getData()` but didnt seem to fit my issue as I dont use models with most of my forms.
What I'm looking for is flexibility to be able to get the the whole `$data` property of a form, rather than just 1 key which is all that is supported with the current `getData()` function.
> Add ability to get all of $data from the form.

- src/Kris/LaravelFormBuilder/Fields/ChildFormType.php
- src/Kris/LaravelFormBuilder/Form.php
- src/views/child_form.php
- src/views/form.php
- tests/FormTest.php
Adds logic to `Form`, `ChildFormType` and respective views, to add the ability to mark fields to not render when calling `->renderForm()` or `->render()`.
When using with `Form`:
```
$form->exclude(['unwanted_field', 'another_field'])->renderForm();
```
When using with `ChildFormType`:
```
$form->child->render(
['exclude' => 
['unwanted_field', 'another_field']
]);
```
Not experienced with phpunit for testing so havnt included tests as when I tried to copy another test and tweak to fit this use-case, Mockery was throwing stuff at me that I dont know how to solve :P
> Add ability to exclude fields from rendering.

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/views/checkbox.php
- src/views/child_form.php
- src/views/choice.php
- src/views/collection.php
- src/views/radio.php
- src/views/select.php
- src/views/text.php
- src/views/textarea.php
- tests/Fields/ButtonTypeTest.php
- tests/Fields/InputTypeTest.php
- tests/Fields/StaticTypeTest.php
Fixes #78 
Replaced all the 
```
array_get($options, 'real_name', $name)
```
with
```
$name
```
for grabbing errors from Laravels error bag.
Multiple Choice doesnt work with this method though, for a field with a "true" name of `form_name[field_name]` the `$name` in the view becomes `form_name[field_name][]` for HTML multiple choice to work obviously.
So at the moment multiple choice fields wont display error messages.
This is a short fix imo, I feel the design could use having views work off a `$htmlName` or whatever which can be manipulated. So `$name` can be always consistent with domain logic.
P.S. Fields edited but not used personally (so dont know how it effects):
- Collection
- Radio (though simple enough should be fine)
> update views to use correct name

- src/Kris/LaravelFormBuilder/Form.php
Hey,
This follows up on past child form issues re: `getName()` getting the html-ified name of `child_form_name[actual_field_name]`
Swapped out `getName()` for `getRealName()` which I added in previous PR so that you're comparing just the `actual_field_name` so it works when doing things like 
```php
{!! form_until( $form->child_form->getForm() , 'field_name' ) !!}
```
Works as intended now for both forms and child-forms.
P.S.
In the example above you can see its a bit janky passing a child form, because child forms are `ChildFormType` rather than just a `Form` a `getForm()` call is needed to get the underlying form instance. We could add in a check in the relevent helper methods so you can just pass the child form itself and it still work, something like:
```php
if( $form instanceOf …
```
> Update renderUntil() to work with child forms

- src/Kris/LaravelFormBuilder/Fields/FormField.php
`! $defaultValue` isnt secure enough and causes type issues for example attempting to set a string of `"0"` evaluates as no default value.
The value of `$defaultValue` when no option is passed, is `false` so just make a hard check for that because nobody should try and set the `default_value` option as "no default value" because that's the default.
> Fix default value bug

- src/Kris/LaravelFormBuilder/Fields/ChildFormType.php
- src/Kris/LaravelFormBuilder/Form.php
- tests/FormTest.php
This PR adds the ability to take a child form and add its fields directly to the parent form.
Added `makeField()` as an abstracted method of generating the `FormField`
Added `compose` which is used the same way as `add()` just only needing `$options` and the `$modify` flag. It creates the child form as usual via the new `makeField()` function, then just adds all the fields from that child form, to the parent form.
I've thrown this together as it fixed my issue of trying to use child forms to help with composition of forms but it messed up using model binding, and this is the best solution anyway I just hadnt thought of it till now :P
> Add form composition

- src/Kris/LaravelFormBuilder/FormHelper.php
- tests/Fields/ButtonTypeTest.php
- tests/Fields/InputTypeTest.php
- tests/Fields/StaticTypeTest.php
- tests/FormHelperTest.php
Hi @kristijanhusak 
Just started formatting all the forms on an app where I'm using the form builder and just noticed (for the first time!) that all labels are converted to title case which isn't really the most flexible output IMO.  Would be better to output as sentence case and if the user want to they can use CSS to convert to title case if required.  Switching to sentence case is likely to output a closer representation of what the author has written for the label in most cases
> Tweak label formatting for greater flexibility

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/RulesParser.php
As discussed in #135 it's now possible to add validation rules and validate forms.
This PR automatically transforms rules to attributes. So a `required` rule will add a `required` attribute, `max` -> `maxlength` or `max`, depending on the type, etc
For pattern validation, the validation message is used to set the `title` attribute, so the browser can show a better message.
Validation types currently supported:
Validations that could perhaps be added, but I skipped because of complex patterns.
- date, date_format (date formats)
- ip address (pattern validation?)
See https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Validation-related_attributes
Not sure about the cleanest implementation or that this should be configurable? If we make sure the HTML5 …
> HTML5 validation attributes

- src/Kris/LaravelFormBuilder/RulesParser.php
I know I added this myself, but I don't feel really confident about this. Regexes are difficult and I don't think we can simply transform php regex to html patterns. It might give okay results for easy cases, but unpredictable for other cases. Best to just let the developer set his own pattern if he needs this.
> Remove regex rule

- src/Kris/LaravelFormBuilder/Form.php
- tests/FormTest.php
I spent a couple hours debugging a problem which was caused by a typo in a field name passed to the "form_until" helper function, which just wraps "renderUntil". Everything after that point was basically getting rendered twice. Ideally such a case would just be caught immediately and an exception would be thrown. Tests are passing for me.
> `renderUntil` method - throw exception if passed a non-existent field name

- src/Kris/LaravelFormBuilder/Console/stubs/form-class-template.stub
Changes the position of the namespace definition to be the same as the new default Laravel style.
> Update form-class-template.stub namespace position

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/Form.php
- src/config/config.php
- tests/Fields/FormFieldTest.php
- tests/FormTest.php
This pull request adds functionality to define a template prefix for a form. It should be fully backwards compatible.
The goal of this change is the ability to quickly copy an entire views/form directory and create an entirely new styling for a form. Using this new style for all the form fields in a form is as simple as setting the `template_prefix` option for the `Form`. This template prefix trickles down into the `getViewTemplate` method for `FormField` as well.
3 tests have been added to check functionality.
If you have any questions or think something should work/be configured differently, I'm happy to discuss!
> Add template prefix functionality

- src/Kris/LaravelFormBuilder/Form.php
- tests/Fields/FormFieldTest.php
- tests/FormTest.php
Before using setFormOptions it would not correctly pull template_prefix
from the options. Leaving it in caused it to be displayed as an
attribute on the form.
I made a separate setter for the template prefix and followed the logic
used for other settings in setFormOptions.
Sorry for the inconvenience and the oversight in my previous pull
request!
> Cleanup template_prefix code

- src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
... through LaravelCollective\HTML in 1.6.40.
Don't know if you already implemented a version check.
> Rudimentary fix to avoid exceptions in Laravel 5.1

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/RulesParser.php
- tests/Fields/FormFieldTest.php
- tests/RulesParserTest.php
As discussed in kristijanhusak/laravel-form-builder#206
This change should be fairly straightforward and shouldn't break existing code. The only side effect might be that the `required` class is added where the user does have the `required` rule but didn't have the `required` option before.
> Add functionality to add required class based on rules

- src/Kris/LaravelFormBuilder/Fields/ChildFormType.php
- src/Kris/LaravelFormBuilder/Fields/ChoiceType.php
- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/Form.php
- src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
- src/Kris/LaravelFormBuilder/FormHelper.php
- tests/Fields/ChildFormTypeTest.php
- tests/Fields/FormFieldTest.php
- tests/FormBuilderTest.php
- tests/FormBuilderTestCase.php
- tests/FormHelperTest.php
- tests/FormTest.php
As discussed in kristijanhusak/laravel-form-builder#206
I'm not sure this is the best way to go about this, but I'm submitting this pull request to start a discussion.
I've opted not to do the generation of the localizable name in the `FormHelper`, because there is no real connection to the form. In addition to that, `FormHelper` is defined as a singleton so setting a language string would make little sense in there.
I have also removed a piece of code from the `choices` field. As described in that commit:
> The array passed is a key value array. To me, it doesn't make sense to pass this value through the label formatter, since it will change (intended) underscores to spaces.
Furthermore, I have only 'enabled' implicit localization for labels that are implicitly determined. I.e.: for …
> Add localizable names/label functionality

- src/Kris/LaravelFormBuilder/FormHelper.php
- tests/Fields/FormFieldTest.php
Laravel translations can be nested and thus the translator will return
an array for these types of translations.  Passing an array into the
FormBuilder where is it expecting a string results in an error when the
form is rendered due to htmlentities not knowing what to do with an
array.  This change akes sure that the returned translation is actually
a string before using it.
I also updated the test to check for this case.
> Add check for nested translations

- src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
When I fixed FormBuilder to be compatible with Laravel < 5.2, I implemented a stupid fix that might throw an exception on Laravel 5.3+.
> Prepared FormBuilder to be compatible with Laravel 5.3+

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- tests/Fields/FormFieldTest.php
Originally proposed by @theshaunwalker in #255 
> Adds the ability to use attr.append_class to append to the attr.class value instead of having to overwrite it. This allows you to use global defaults and not have to hard code them if you just want to add more classes.
I've rewritten it a bit, made sure that `class_append` would not show up as an actual attribute and wrote tests covering appending to wrapper, label and field.
> Add ability to append to class attribute for wrapper, label and field

- src/Kris/LaravelFormBuilder/Form.php
- tests/FormTest.php
Since the following pattern happens for almost every form I'd say, we can create something that is a little less verbose. This code in the controller:
```
$form = magicallyCreateSomeForm();
if (!$form->isValid()) {
return redirect()->back()->withErrors($form->getErrors())->withInput();
}
```
Would become:
```
$form = magicallyCreateSomeForm();
$form->redirectIfNotValid();
```
Or even this if you don't need really the need the form object after validating:
```
magicallyCreateSomeForm()->redirectIfNotValid();
```
I figured the `Form` class would be a good spot for this, although one could argue that a `redirectIfNotValid($form)` function on the `FormBuilderTrait` might work as well.
A test has been written to ensure a redirect with input and errors is returned when verification fails. I've …
> Redirect when verification fails

- src/Kris/LaravelFormBuilder/Events/AfterFieldCreation.php
- src/Kris/LaravelFormBuilder/Events/AfterFormCreation.php
- src/Kris/LaravelFormBuilder/Events/AfterFormValidation.php
- src/Kris/LaravelFormBuilder/Events/BeforeFormValidation.php
- src/Kris/LaravelFormBuilder/Form.php
- src/Kris/LaravelFormBuilder/FormBuilder.php
- src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
- tests/FormBuilderTest.php
- tests/FormBuilderTestCase.php
- tests/FormTest.php
Events added:
* AfterFieldCreation (Form, FormField)
* AfterFormCreation (Form)
* BeforeFormValidation (Form, Validator)
I think the names are obvious. With these events, an app or package could do something like:
```
public function onCreateFormField(AfterFieldCreation $event) {
if ($label = $event->getField()->getOption('label')) {
$event->getField()->setOption('label', 'x ' . $label);
}
}
public function onCreateForm(AfterFormCreation $event) {
$event->getForm()->setFormOption('novalidate', '');
}
public function onValidateForm(BeforeFormValidation $event) {
$validator = $event->getValidator();
$validator->after(function() use ($validator) {
rand(0, 1) and $validator->messages()->add('field', 'Error!');
});
}
```
> #253 Added events

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- tests/Fields/FormFieldTest.php
The `required` class was not added when client side validation is not enabled. I think it makes sense to add the `required` class to labels even when validation is not enabled. My mistake in #209 😉 
I also changed the test names I wrote back then to be a little more descriptive and added a check for the `required` attribute as well.
If possible, can we create a new version from this soon? I'd love to push this fix to production without having to use my fork as the source for the package. Thanks so much!
> Fix adding required class to labels when client validation is disabled

- src/Kris/LaravelFormBuilder/Fields/ChildFormType.php
- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/Fields/StaticType.php
- src/Kris/LaravelFormBuilder/Form.php
- src/Kris/LaravelFormBuilder/FormHelper.php
- tests/FormTest.php
Adds a public `$form->getValidatedValues()` function to extract all Request values according to the submitted form, not according to the submitted data. Uses all fields' `getAllAttributes()` to collect a flat list of all attributes, including all child forms and theirs etc.
The main function (`getValidatedValues`) is somewhat of a misnomer, because it doesn't actually validate, and the returned values don't have to be validated in order to call it, but I couldn't find a better name.
**Usage:** instead of
$values = $request->all();
call
$values = $form->getValidatedValues();
> #246 +Form->getValidatedValues()

- src/Kris/LaravelFormBuilder/Form.php
- src/Kris/LaravelFormBuilder/FormHelper.php
- tests/FormTest.php
Added `FormHelper->transformToBracketSyntax()`, which helps in fixing the field's name. It's not super pretty, but I think it handles all cases.
> #250 bugfix in doubly nested field name

- src/Kris/LaravelFormBuilder/Fields/ChildFormType.php
- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/helpers.php
Follow-up of https://github.com/kristijanhusak/laravel-form-builder/pull/256 which was too much.
With these 2 additions, you can make a reusable fields tpl that renders several fields at once:
In `form.php`:
{{ form_rows(form, ['name', 'age']) }}
In `child_form.php`:
{{ form_rows(field, ['name', 'age']) }}
because `form` is the form and `field` is the child form, kinda.
I don't like the `$form` argument in `form_rows()` though. It can be a `Form` or a `ChildFormType`, and both work because of `ChildFormType::__call()`, but you can't type hint that...
> #244 +form & field vars in field render, +form_rows() helper

- src/Kris/LaravelFormBuilder/Fields/ButtonType.php
I forgot one. Submit buttons don't need values. If you `getFieldValues()` with the optional argument to its default (TRUE), it adds NIL values for 'missing' input like a submit button.
> No getFieldValues() for (submit) buttons

- src/Kris/LaravelFormBuilder/Fields/CollectionType.php
- src/Kris/LaravelFormBuilder/Fields/RepeatedType.php
- src/Kris/LaravelFormBuilder/FormHelper.php
More `getFieldValues()` bugs.
* `RepeatedType` skipped the repeated value, because it wasn't in the attributes list
* `CollectionType` added the **entire** data blob for that element, no matter the format, so now it collects children like ChildFormType does
I checked all ParentType components and I think this is it. The rest are radio buttons etc, so they should be included as 1, not per child element.
Aside: I expected CollectionType to validate with `*`: `locations.*.name`, `locations.*.street` etc, but it validates only explicitly present elements, so `locations.0.street`, `locations.1.street` etc. How would you validate a new location added with JS? It's not in the validation list. (And now it's not in the attributes list, so it won't be included in `getFieldValues()`).
> Bugfix in getFieldValues() for CollectionType and RepeatedType

- src/Kris/LaravelFormBuilder/Fields/ChildFormType.php
- src/Kris/LaravelFormBuilder/Form.php
- src/Kris/LaravelFormBuilder/FormHelper.php
- tests/FormBuilderTest.php
- tests/FormTest.php
Added
* `alterFieldValues()` to `Form` to alter that form's values
* `alterFieldValues()` to `FormHelper` to call that alter and recurse through fields
* `alterFieldValues()` to `ChildFormType` to act on and recurse through child forms
Three different functions with the same name... Might not be the best.
With test!
There's still something missing and it might be part of this: form specific validation. If a child form has an image and another form has validation errors, the child form wants to add a validation message to reupload the image. The parent form could do this in `isValid()`, but that's not called for child forms... Ideas?
> Alter field values

- src/Kris/LaravelFormBuilder/Console/FormGenerator.php
- src/Kris/LaravelFormBuilder/Console/FormMakeCommand.php
- src/Kris/LaravelFormBuilder/Events/AfterFieldCreation.php
- src/Kris/LaravelFormBuilder/Events/AfterFormCreation.php
- src/Kris/LaravelFormBuilder/Events/AfterFormValidation.php
- src/Kris/LaravelFormBuilder/Events/BeforeFormValidation.php
- src/Kris/LaravelFormBuilder/Facades/FormBuilder.php
- src/Kris/LaravelFormBuilder/Fields/ButtonGroupType.php
- src/Kris/LaravelFormBuilder/Fields/ButtonType.php
- src/Kris/LaravelFormBuilder/Fields/CheckableType.php
- src/Kris/LaravelFormBuilder/Fields/ChildFormType.php
- src/Kris/LaravelFormBuilder/Fields/ChoiceType.php
- src/Kris/LaravelFormBuilder/Fields/CollectionType.php
- src/Kris/LaravelFormBuilder/Fields/EntityType.php
- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/Fields/InputType.php
- src/Kris/LaravelFormBuilder/Fields/ParentType.php
- src/Kris/LaravelFormBuilder/Fields/RepeatedType.php
- src/Kris/LaravelFormBuilder/Fields/SelectType.php
- src/Kris/LaravelFormBuilder/Fields/StaticType.php
- src/Kris/LaravelFormBuilder/Fields/TextareaType.php
- src/Kris/LaravelFormBuilder/Form.php
- src/Kris/LaravelFormBuilder/FormBuilder.php
- src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
- src/Kris/LaravelFormBuilder/FormBuilderTrait.php
- src/Kris/LaravelFormBuilder/FormHelper.php
- src/Kris/LaravelFormBuilder/RulesParser.php
Fixed some inconsistencies 
* Always using implode instead of 'join' once
* return types
* . on the end of a comment
* { class opening on new row. (same for functions)
* inheritdoc where possible
* properties don't require naming the $foo in the comment.
* Comments are no longer questions. 
* @params have types now.
* Naming boolean -> bool
> Improved DocComments, params especially their type, returns, line endings

- src/Kris/LaravelFormBuilder/Fields/ChildFormType.php
- src/Kris/LaravelFormBuilder/Form.php
- tests/Fields/CollectionTypeTest.php
This is my attempt to fix this issue https://github.com/kristijanhusak/laravel-form-builder/issues/279
When you make a collection of child forms, the bound model is the parent's model rather than the child's model.
For example, if I have a UserProfileForm with a collection of child forms called ProductForm, when accessing the getModel() of the product form I get back the user model from UserProfileForm when it should be returning the product model.
I also attempted to write a test for this.
> Fix child models not being bound correctly in collection forms

- src/Kris/LaravelFormBuilder/Fields/EntityType.php
- tests/Fields/EntityTypeTest.php
Currently there is a fixed default value of 'id' for the property_key name. This is because the default primaryKey column in Laravel is also 'id'. But as we already instantiate the entity, this commit just requests from the entity what its key name is.
> Use primaryKey of model as default property_key

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/FormHelper.php
- tests/RulesParserTest.php
From #340 
This allows the developer to extend the RulesParser to add their own 'rule to attribute' logic.
> +Extensible RulesParser

- src/Kris/LaravelFormBuilder/Fields/ButtonGroupType.php
Button group field type was not working out of the box due to a non-existent path being set. Fixed the button group template path to match the rest of the types.
> Bug Fix - ButtonGroupType.php

- src/helpers.php
Adds a new `form_fields()` helper function which renders the contents of the form without the opening and closing `<form>` tags.
> Adds form_fields helper

- src/views/choice.php
Now we can set up child options, for example **size** or **VueJS attributes**.
PHP:
```
$this->add('languages', 'choice', [
'choices' => ['en' => 'English', 'fr' => 'French'],
'multiple' => true
]);
```
Blade:
`{!! form_row($form->languages, ['attr' => ['size' => 10, '@input' => 'update']]) !!}`
Output before:
`<select class="form-control" multiple="1" id="languages[]" name="languages[]">`
Output after:
`<select class="form-control" multiple="1" size="10" @input="update" name="languages[]">`
> ChoiceType: Deal with child options

- src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
- src/Kris/LaravelFormBuilder/Traits/ValidatesWhenResolved.php
- tests/Fixtures/TestController.php
- tests/Fixtures/TestForm.php
- tests/FormBuilderValidationTest.php
This PR adds the ability to automatically validate form objects when they get resolved through Laravels IOC container.
The behavior is similar to the FormRequest validation, so you only need to typehint the form object in your controller. If the validation fails, the form will automatically trigger the `redirectIfNotValid` method.
Usage:
```php
<?php
use Kris\LaravelFormBuilder\Form;
use Kris\LaravelFormBuilder\Traits\ValidatesWhenResolved;
class TestForm extends Form
{
use ValidatesWhenResolved;
public function buildForm()
{
$this->add('name', 'text', ['rules' => ['required', 'min:3']]);
}
}
```
```php
<?php
class TestController
{
public function validate(TestForm $form)
{
// Everything in here is automatically valid!
}
}
```
> Add ability to automatically validate Form classes

- src/Kris/LaravelFormBuilder/Fields/CollectionType.php
Use input() to correctly return the data from the current request so that, if it contains multiple rows, those rows can be read in as children of the Collection field.
> Bug-fix: CollectionType.php

- src/Kris/LaravelFormBuilder/Form.php
- src/Kris/LaravelFormBuilder/FormHelper.php
Prevent ```Custom field [name] already exists on this form object.``` error on addCustomField and rebuildForm.
> Check if custom field already defined on rebuildForm

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/views/checkbox.php
Just checked this with inputs and textareas.
This produces nothing:
```
'rules' => 'max:25',
```
This produces `required="required" maxlength="25"`
```
'rules' => 'required|max:25',
```
I very quickly created this PR, but I'm not sure it's actually a bug.
What do you think?
> If a form field is not required, it won't have any client validation enabled

- src/Kris/LaravelFormBuilder/Fields/ChoiceType.php
- tests/Fields/ChoiceTypeTest.php
sometimes maybe need to override choices the field with advanced logic, I know there is `query_builder` for `Entity` but its limit for a query & data from the database, but now can override data of all fields they base of `ChoiceType` field
Also, added simple test unit for this PR
example for using with `Entity` field
```php
$this->add('languages', 'entity', [
'class' => 'App\Language',
'data_override' => function ($choices, $field) {
$choices['testID’] = 'test';
return $choices;
}
]);
```
> [NEW][Features] Added support override data of ChoiceType

- src/Kris/LaravelFormBuilder/Fields/ChildFormType.php
- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/Form.php
- tests/Fields/ChildFormTypeTest.php
- tests/Fields/FormFieldTest.php
In some of our projects we use a language line system of:
```
'fields' => [
'email' => [
'label' => 'Email address',
'placeholder' => '',
'tooltip' => '',
'help' => '',
],
'password' => [
'label' => 'Password',
'placeholder' => '',
'tooltip' => '',
'help' => '',
],
'submit' => [
'label' => 'Log in',
],
],
```
This doesn't work with the current `language_name` functionality and would force us to manually write `trans('customer.login.fields.email.label')` for all fields.
This new functionality is fully backwards compatible with the old code, as long as you didn't use `translation_template` for custom functionality yet (highly unlikely).
Would love to hear what you think, and if you like it when you plan to release a new version.
Thanks in advance!
> Add translation template for labels

- src/Kris/LaravelFormBuilder/Fields/ParentType.php
- tests/Fields/EntityTypeTest.php
The ParentType FormField's only copies the options supplied on FormField creation to their children. If you call 'setOption/setOptions' after creating e.g. an 'EntityField' the option is never passed to the child. This commit changes that behaviour by calling 'setOption/setOptions' on all children as well. See added test in EntityType for an use-case.
> ParentType not pushing options to children

- src/views/static.php
I didn't use Laravel's helper method e() to escape because I sense the templates were built avoiding any tight dependence with Laravel, so I tried to keep it that way.
> Escape static field value

- src/Kris/LaravelFormBuilder/Fields/CollectionType.php
Checking trueness on empty array returns false, so while creating form, request data is ommited. Fixes #313
> fixed error with collection type

- src/views/checkbox.php
- src/views/radio.php
#416 Move label position before help_block for checkbox and radio button.
> Fix: lable and help_block position bug with radio and checkbox

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/Form.php
- src/Kris/LaravelFormBuilder/FormHelper.php
Hi Kris, thanks for this project. Very helpful. :)
> Allow for form level configuration

- README.md
- src/Kris/LaravelFormBuilder/Field.php
Hello Kris
I create const in interface for Form class to easy to use fields and faster to found.
When I use this package I should check the uses field every time.
when we use const we don't need search any time for special field
this form is readable than origin Form Class:
`class SongForm extends Form {
public function buildForm() {
$this ->add('name', Form::FIELD_TEXT) 
->add('lyrics', Form::FIELD_TEXTAREA) 
->add('publish', Form::FIELD_CHECKBOX); }
}`
> add const to all types

- src/Kris/LaravelFormBuilder/Field.php
Hey
I was just using this as stumbled upon that error when importing via the `Field` constants.
Cheers
> Fixed: "datetime_local" to "datetime-local" as "_local" is not supported

- src/Kris/LaravelFormBuilder/Events/AfterCollectingFieldRules.php
- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/Fields/ParentType.php
- src/Kris/LaravelFormBuilder/Form.php
- src/Kris/LaravelFormBuilder/FormBuilder.php
- src/Kris/LaravelFormBuilder/FormHelper.php
- src/Kris/LaravelFormBuilder/Rules.php
My apps have custom fields and custom validators, but I want to use the form builder as pure as possible. An event for altering field rules would be perfect. Event `BeforeFormValidation` is too late, because it has prepared the entire validator already.
Patch is almost completely backward compatible, but not quite. The return type of `FormField::getValidationRules()` has changed from `array` to `Rules`. For new fields that's fine (because `Rules::fromArray`), but if a developer extends an existing field and expects an array from `parent::getValidationRules()`, that will crash.
> Better field rules collection, with AfterCollectingFieldRules event

- src/Kris/LaravelFormBuilder/Fields/ParentType.php
I use `AfterFieldCreation` to set options and add classes to some fields automatically. But if I `setOption` a `ChildFormType`, the option is copied to all children. For some options that's good, but for some it's not (field type class).
With this new option, the developer can choose not to copy options:
$events->listen(AfterFieldCreation::class, function(AfterFieldCreation $event) {
$event->getField()->setOption('copy_options_to_children', FALSE);
$event->getField()->setOption('wrapper.class', 'foo');
});
The default is `true`, so it's fully bc.
> don't always automatically copy parent setOption(s) to children

- src/Kris/LaravelFormBuilder/Fields/CollectionType.php
If you always want POST data to be the guide of which collection items to validate & accept. If your model has a 2 item collection, and your POST submits 7 items, those 7 items will be validated, and returned by `getFieldValues`.
> +collection option prefer_input

- src/Kris/LaravelFormBuilder/FormHelper.php
A subform with checkboxes, with none checked, submits no values. If the complete form's values are retrieved with `getFieldValues(false)` (no nulls), the subform is empty (`null`), but `alterFieldValues` always expects an array.
I think I made this originally =) Sorry! Apparently I'm also the only one who uses it =)
> Make sure subvalues is an array

- tests/FormBuilderTest.php
Hi, I've changed some PHP keywords to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!
> Change PHP keywords to comply with PSR2

- src/Kris/LaravelFormBuilder/Fields/EntityType.php
This makes it possible to react to the current model values in
the query builder.
Example:
A "category" dropdown of type "entity".
Its queryBuilder adjusts the query to only show public categories.
When editing a model that already has a non-public category selected,
the query builder is now able to take this into account and
show public categories plus the currently selected non-public/internal
category.
> Pass form instance to "entity" field queryBuilder

- src/Kris/LaravelFormBuilder/Fields/CollectionType.php
Without this patch a `ChildFormType` without data (e.g. a collection's `empty_row` item) will set the parent model as its model.
In `ChildFormType::getClassFromOptions()`:
```
$options = [
'model' => $this->getOption($this->valueProperty) ?: $this->parent->getModel(),
// ...
];
```
I don't know why, it's weird, but it might have a reason, so I won't break that.
This patch allows the parent form to define the `empty_row`'s data, so not `null` is passed through, so not the parent model is used:
```
// In the parent form: e.g. InvoiceForm
// $this->model instanceof Invoice
$this->add('items', 'collection', [
'label' => 'Items',
'type' => 'form',
// 'data' => [], // Or empty because $this->model->items is empty
'empty_row' => new InvoiceItem(), // truthy, but not `true`
'options' => [
'class' …
```
> add explicit collection empty row data

- src/Kris/LaravelFormBuilder/FormHelper.php
If the parent form's `alterFieldValues()` comes last, it has ultimate control, over its child forms too. Otherwise it can't change/unset/move child form values.
> alterFieldValues() order+

- composer.json
All deprecated helpers are removed in PR #504 so I think it would work fine on Laravel 6.0.
> Add support Laravel 6.0

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/Form.php
- tests/FormTest.php
Added a new method `getNameKey` to Form class to align to the method `\Kris\LaravelFormBuilder\Fields\FormField::getNameKey`.
This is useful when creating nested validation rules.
> Added `getNameKey` method to Form class

- src/Kris/LaravelFormBuilder/Form.php
- tests/FormTest.php
When rendering the form with `$formOptions` contains any non-string value like
```php
class MyForm extends BaseForm
{
protected $formOptions = [
'foo' => ['bar'], // array value
];
}
```
Template:
```php
// This will throw an exception.
<?= Form::open($formOptions) ?>
```
Move form attributes to `$formOptions['attr']`, only pass `$formOptions['attr']` and reserved options to the view.
After this PR:
```php
// in template the `foo` was removed from `$formOptions`, 
// so the following code won't throw exception.
<?= Form::open($formOptions) ?>
// but we can still access the original option 
// by calling `$form->getFormOption('foo')`
```
> Fix exception thrown if `formOptions` contains any non-string value.

- composer.json
- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/FormHelper.php
- src/Kris/LaravelFormBuilder/RulesParser.php
- tests/Console/FormGeneratorTest.php
- tests/Fields/ButtonTypeTest.php
- tests/Fields/CollectionTypeTest.php
- tests/Fields/EntityTypeTest.php
- tests/Fields/FormFieldTest.php
- tests/Filters/FilterResolverTest.php
- tests/FormBuilderTest.php
- tests/FormBuilderTestCase.php
- tests/FormBuilderValidationTest.php
- tests/FormHelperTest.php
- tests/FormTest.php
- tests/RulesParserTest.php
`\Kris\LaravelFormBuilder\FormHelper::mergeOptions` merges options with `rules` option behavior incorrectly. It should replace the rules entirely or just appends new rules. 
The current strategy may cause the merged rules duplicated, and has no way to "replace" the default rules entirely.
> Fix `mergeOptions` behavior

- .github/workflows/test.yml
Although Travis CI works fine too, since this is hosted on GitHub and since you're going to start on a V2, I made the guess to add GitHub Actions support to the repo.
Currently test PHP 5.6 - 7.4, with releases from source (`--prefer-source`) and from releases (`--prefer-dist`), since users are more likely to get assets from the latter.
There's an option to add Windows and Mac OS to the matrix, but it'd result in 18 jobs, which seems  a bit too enthusiastic.
> Added Github Actions

- src/Kris/LaravelFormBuilder/Fields/ParentType.php
The parent class FormField does this, so ParentType should do, too
> Make ParentType::setOption(s) return $this

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- tests/FormBuilderTestCase.php
- tests/FormTest.php
**What has changed?**
Allows the model attribute name to be defined as option to resolve the value from the model, useful for when an accessor is used to modify the value on retrieval, but it should be stored in the database as the field name.
**Personal use case example**
```
//old method
$form->add('coverages', 'choice', [
'selected' => $this->getModel()->form_coverages,
]);
//new method
$form->add('coverages', 'choice', [
'property' => 'form_coverages',
]);
```
What did this fix for me?
Being able to use `setValue` on the form field afterwards. With hard defining the selected (default) value, the `setValue` method becomes unusable since it early returns if the field has a default value.
This is an update/cleanup from https://github.com/kristijanhusak/laravel-form-builder/pull/596 to …
> Allow use of the property option to resolve value

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- tests/FormTest.php
We should not use the `property` option on an instance of the `EntityType` field, because it uses the `property` option to resolve the display name of the field. 
There was no unit test that validated that the value of the entity in the existing model was set as the value of the entity field.
This PR fixes the issue for the `EntityType` field and adds the unit test to validate this works.
> Fixes issue where the entity field was not set to the model value

- src/helpers.php
This PR fixes a bug caused by my last PR (#607), view paths generated from package's namespace so we can use most relevant view.
> Load error and help_block from package namespace instead of hardcoded path

- phpunit.xml
- src/Kris/LaravelFormBuilder/Fields/FormField.php
- tests/Fields/CollectionTypeTest.php
- tests/FormTest.php
Bug introduced in #598 because the `property` option already exists in `collection` fields with default value `'id'`, so it **always** takes the `id` property for collection fields, which is always wrong.
Bug only noted in #620, because I suck, and automated tests didn't catch above bug.
Only fix IMO: rename the general `property` option to `value_property`, so it doesn't clash with the `collection` field option. Can't rename that one, because it's much older and officially released. Sorry @SanderMuller but that's a breaking change for you.
Added a CollectionType test to make sure the correct value is used.
I need a professional opinion here @kristijanhusak because I screwed this up before.
I will update the docs for `value_property` after merge.
> Fixes bug from #620 introduced in #598: general field option 'property' clashes with collection field

- src/Kris/LaravelFormBuilder/Fields/CollectionType.php
- tests/Fields/CollectionTypeTest.php
This is the better version of #519, with the same intent:
- Keep model input as models during validation errors, so child forms always have a predictable model object as `$this->model`, instead of an array.
- Make all not-model collection rows from a predictable real model (like prototype and empty row), which currently get the parent model as the child model, which is just weirdd.
Usage:
```
class SiteCostsForm extends Form {
public function buildForm() {
$this->add('costs', 'collection', [
'type' => 'form',
'prototype' => true,
'prefer_input' => true,
'empty_model' => fn() => new SiteCost(), // <<<
'options' => [
'class' => SiteCostForm::class,
],
]);
}
}
```
`empty_model` will be run for every row that doesn't have a model:
- empty_row
- prototype
- **new** rows from form input …
> Use collection empty_model option for keeping model data intact during validation (errors)

- .github/workflows/test.yml
- composer.json
- tests/Fields/CollectionTypeTest.php
- tests/Fields/FormFieldTest.php
- tests/FormTest.php
PHP 7.1 and 7.2 aren't relevant anymore.
dev-requiring `orchestra/testbench` version `~3.6` capped Laravel test version at 6.x, which is pretty old now.
> Use modern versions of PHP and Laravel for testing

- src/Kris/LaravelFormBuilder/Fields/CollectionType.php
I can't believe I missed this. During POST, when the form is being built, if the collection has `prefer_input` enabled, the raw POST data is used as collection data, instead of the configured data. If `empty_model` is enabled, that raw POST data should be formatted into models too. Not just after validation errors, when the form is being rebuilt for input, but also during POST, when the form is being rebuilt for validation.
> improves collection formatInputIntoModels() during postback

- composer.json
This should allow this package to be used with Laravel 9. Did a quick test and everything seems to work :) Please note that Laravel 9 requires PHP8+
I wasn't able to get the unittests fully running, so if someone is able to verify them that would be great!
Also fixes issue https://github.com/kristijanhusak/laravel-form-builder/issues/667
> Allow Laravel ^9

- src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
Allow clients to turn off escaping for labels with `Form::customLabel()`.
> Allow Escape HTML via customLabel()

- src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
- src/config/config.php
- tests/FormBuilderServiceProviderTest.php
- tests/FormBuilderTestCase.php
Customizable classes by config.
e.g.
```php
'form_builder' => \Kris\LaravelFormBuilder\FormBuilder::class,
'helper' => \App\Form\MyFormHelper::class,
```
```php
class MyFormHelper extend FormHelper
{
public function mergeOptions(array $targetOptions, array $sourceOptions)
{
return $targetOptions + $sourceOptions;
}
}
```
> Customizable classes by config.

- src/Kris/LaravelFormBuilder/Form.php
- tests/Fields/FormFieldTest.php
Added `isPlain()` method for modified plain form.
```php
use Kris\LaravelFormBuilder\Form;
class ModifiedPlainForm extends Form
{
protected function isPlain()
{
return static::class === self::class;
}
}
```
```php
$formBuilder->setFormClass(ModifiedPlainForm::class);
```
> Added `isPlain()` method for modified plain form

- src/Kris/LaravelFormBuilder/Fields/ChoiceType.php
- src/Kris/LaravelFormBuilder/Fields/SelectType.php
- src/views/select.php
- tests/Fields/SelectTypeTest.php
- tests/FormTest.php
Added ability to pass attributes to individual options in select/choices
For example, I want to disable certain option in my select/choice list
Pass two-dimensional array with 
['option_key' => ['attribute' => 'attribute_value']] into `option_attributes` option.
Inspired by the 5th parameter of LaravelCollective Form::select()
https://github.com/LaravelCollective/html/blob/6.x/src/FormBuilder.php#L614
Example:
```php
<?php
namespace App\Forms;
use Kris\LaravelFormBuilder\Form;
class ExampleForm extends Form
{
public function buildForm()
{
$this->add('languages_select', 'select', [
'choices' => ['en' => 'English', 'fr' => 'French', 'zh' => 'Chinese'],
'choice_options' => [
'wrapper' => ['class' => 'choice-wrapper'],
'label_attr' => ['class' => 'label-class'],
],
'selected' => ['en'], …
```
> Added ability to pass attributes to individual options in select/choices

- src/Kris/LaravelFormBuilder/Form.php
- src/Kris/LaravelFormBuilder/FormHelper.php
- tests/FormBuilderTestCase.php
> str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated
Today str_replace is returning a blank string if a null value is specified as subject
> Fix deprecation message if str_replace receive a null value in FormHelper

- phpunit.xml
- src/helpers.php
- src/views/checkbox.php
- src/views/child_form.php
- src/views/choice.php
- src/views/collection.php
- src/views/label.php
- src/views/radio.php
- src/views/select.php
- src/views/static.php
- src/views/text.php
- src/views/textarea.php
- tests/Fields/FormFieldTest.php
- tests/Fields/InputTypeTest.php
- tests/FormBuilderTestCase.php
- tests/resources/views/test-label.php
new option for label template and moved rendering label to `label.php` template file for all templates with label. It simplifies extension of way label is rendered and allows to add custom html to labels. Works for every field (by extending `label.php` file) or for individual field (by providing `label_template` value pointing proper template file).
> label_template option

- src/Kris/LaravelFormBuilder/Fields/CollectionType.php
`empty_model` only works for Eloquent models, but it's also useful for an array of data. In GET that's used for the `prototype` and `empty_row` children. In POST it's used as a basis to put POST data into. Without `empty_model`, the parent model is used, which is weird. (That hasn't changed.) So it's always nice to have an `empty_model`, even if it's not a real `Model`.
> Smarter formatInputIntoModels for non-Models

- .gitignore
- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/Fields/RepeatedType.php
- tests/Fields/RepeatedTypeTest.php
- adding `same:` rule to first field of repeated type
- proper handling of rules on repeated field itself and first subfield
resolves issue #447
> refs #447: adding `same:` rule automatically to repeated field type

- src/Kris/LaravelFormBuilder/Fields/ChoiceType.php
- src/Kris/LaravelFormBuilder/Fields/CollectionType.php
- src/Kris/LaravelFormBuilder/Fields/FormField.php
- src/Kris/LaravelFormBuilder/Fields/ParentType.php
- src/config/config.php
- tests/Fields/ChoiceTypeTest.php
- tests/Fields/CollectionTypeTest.php
- tests/Fields/EntityTypeTest.php
Fields extending `ParentType` don't act properly when disabled. For example `ChoiceType` with `required` rule is not disabled even if asked nicely with `disable()` method. This is due to fact `attr` option gets copied to children from parent while rendering but it doesn't contain `disabled` attribute after `disable()` method was called.
Fixed `disable()` and `enable()` method to act upon `ParentType` field itself before populating information to children. Added functionality tests to all derivatives (as ParentType is abstract and has no tests written so far).
Don't know why it ads some code from previous PR that was already merged. Those changes were made during Pull Request review.
> ParentType  disable()/enable() fix

- src/Kris/LaravelFormBuilder/Fields/CollectionType.php
Collection children don't have a label by default, but an automatic label is assigned anyway. You can already assign specific labels after creating the collection field:
```php
foreach ($this->getField('settings_collection')->getChildren() as $formfield) {
$formfield->setOption('label', $formfield->getForm()->getModel()->name);
}
```
but that's not pretty. Much prettier is a callback in the collection options:
```php
$this->add('settings_collection', 'collection', [
'label' => "Settings",
'type' => 'form',
'prototype' => false,
'empty_row' => false,
'options' => [
'class' => MySettingForm::class,
'label' => function(MySetting $setting, ChildFormType $formfield) {
return $setting->name;
},
],
]);
```
> Allow collection option label to be a callback for dynamic child label

- src/Kris/LaravelFormBuilder/RulesParser.php
fix for #719, simple escape for invalid character.
> issue 719: fixed numeric pattern

- src/Kris/LaravelFormBuilder/Fields/FormField.php
- tests/Fields/CheckableTypeTest.php
- tests/Fields/FormFieldTest.php
- tests/FormBuilderTestCase.php
- tests/FormTest.php
`class_append` didn't work for field types with specific config/classes.
Config:
```php
return [
'defaults' => [
'field_class'         => 'form-control',
'checkbox' => [
'field_class' 		=> 'form-check-input',
],
],
];
```
Add field:
```php
$this->add('mycheckbox', 'checkbox', [
'label' => "Wadever",
'attr' => ['class_append' => 'custom-checkbox'],
]);
```
That `<input>` would have `class="form-check-input"`, not `form-check-input custom-checkbox`, because `setDefaultClasses()` (with `form-check-input`) happened after `prepareOptions()` (with `class_append`/`custom-checkbox`), so the custom classes was added and then immediately overwritten.
> field (css class) defaults+
