kristijanhusak/laravel-form-builder

README.md
src/Kris/LaravelFormBuilder/Console/FormMakeCommand.php

This is your call, but I thought I would suggest this since I keep finding myself typing the command backward.

Rename form:make to make:form for consistency with other Laravel generators

---

src/Kris/LaravelFormBuilder/FormHelper.php

Typo in FormHelper.php

---

src/Kris/LaravelFormBuilder/Fields/CheckableType.php
src/Kris/LaravelFormBuilder/Fields/ChildFormType.php
src/Kris/LaravelFormBuilder/Fields/ChoiceType.php
src/Kris/LaravelFormBuilder/Fields/CollectionType.php
src/Kris/LaravelFormBuilder/Fields/EntityType.php
src/Kris/LaravelFormBuilder/Fields/FormField.php
src/Kris/LaravelFormBuilder/Form.php
src/views/checkbox.php
src/views/radio.php
src/views/static.php
src/views/text.php
src/views/textarea.php
tests/Fields/InputTypeTest.php
tests/Fields/StaticTypeTest.php
tests/FormBuilderTestCase.php
tests/FormTest.php

This is another version of this PR https://github.com/kristijanhusak/laravel-form-builder/pull/111.
@theshaunwalker 
I done this other way, and all tests are passing. Also added those 2 tests from your PR, and they are passing properly.
There were more places to change this, that's why your PR's tests are failing.
I would really appreciate if you could test this PR by yourself to see if it's working.

Rename default_value to value, and use default_value as fallback value.

---

_posts/2015-05-24-collection.md

Add doc for "empty_row" option on CollectionType
Update "options" default value according to code

Update doc for CollectionType

---

src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php

Found 2 api-changes in laravelcollective/html that stopped artisan from working. Missing was `$app['view']`.

little fixes for laravelcollective/html 5.2

---

CHANGELOG.md

Fixed version number

---

README.md
src/config/config.php

Examples follow Laravel's PSR-2 coding style; PHP 5.5 class name resolution since 1.6.40 requires PHP 5.5

Coding style & class name resolution for examples

---

src/Kris/LaravelFormBuilder/Form.php
tests/FormTest.php

I also removed the test.
This refers to #149.

Avoid exceptions on non-existing fields

---

_site/overview/commands.html

Hello
My guess is wrong
change  "form:make " to "make:form"

"form:make " to "make:form"

---

_posts/2015-08-06-validation.md

* Use `$form->getFieldValues()` instead of `$request->all()` because it's safer
* Point to `$form->redirectIfNotValid()` because it's cool

#246 gh-pages update for Form::getFieldValues()

---

.travis.yml
composer.json
src/Kris/LaravelFormBuilder/Fields/EntityType.php
tests/Fields/EntityTypeTest.php

The lists method on the Collection, query builder and Eloquent query builder objects has been renamed to pluck. The method signature remains the same.

Laravel 5.3 support

---

src/Kris/LaravelFormBuilder/Fields/ButtonGroupType.php
src/Kris/LaravelFormBuilder/FormHelper.php
src/config/config.php
src/views/buttongroup.php

Implementation for Button groups ( fix for #288 ).
Example & HTML Result are documented here:
https://github.com/kristijanhusak/laravel-form-builder/issues/288#issuecomment-263068015

Buttongroup

---

composer.json
src/Kris/LaravelFormBuilder/Form.php
src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
src/Kris/LaravelFormBuilder/FormHelper.php
tests/Fields/CollectionTypeTest.php
tests/FormBuilderTestCase.php
tests/FormTest.php

Added Laravel 5.4 compatibility

---

src/Kris/LaravelFormBuilder/FormBuilder.php

Allows any service provider to change the plain form class to any extension of the default Form class.

#319 Configurable plain form class

---

README.md
src/Kris/LaravelFormBuilder/FormBuilder.php
tests/FormBuilderTest.php

Hi
By this changes creating form will be possible without creating form classes.
I believe this changes help us to make form system that users can create costume form themselves.

creating forms with simple arrays

---

src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php

`Illuminate\Session\Store::getToken()` is in Laravel 5.5 only `Illuminate\Session\Store::token()`

Laravel 5.5 compatibility

---

src/views/static.php

Because sometimes you do want HTML.

html escape with e() to respect Htmlable

---

src/Kris/LaravelFormBuilder/Fields/EntityType.php

Allow you to set EntityType property option value to callback function.
eg.
`'property' => function(User $user) {
return $user->completName();
},`

EntityType, property accept callback function

---

src/Kris/LaravelFormBuilder/Form.php

Original issue: #448 by @ryanscherler
I don't like at all how filters change the global request data, but that's how they work. This fixes the scope problems. Fields in subforms didn't work. Fields like `address[street]` didn't work. This fixes both, but I don't like it at all. I'd love to put the filter logic in `alterFieldValues()` (so only through `getFieldValues()`), but that would break @unckleg's code (#376).

fixes #448: filters form subform fields

---

src/Kris/LaravelFormBuilder/Fields/FormField.php

now you can build your form in your queue if you need to calculate data with it

errors when session not set.

---

README.md

If I understood correctly, I added how to store / update a model after a form submit.
I don't know if it's the correct way, but works for me.

Add store / update in readme.md

---

composer.json

Hi @kristijanhusak,
Laravel 7 is released and I've tested your package on my app using Laravel 7. It's still working fine.
There is no change related to your package in Laravel 7 so I think you should support this version.
Thanks for the great package!

Add support Laravel 7

---

src/helpers.php
src/views/button.php
src/views/checkbox.php
src/views/child_form.php
src/views/choice.php
src/views/collection.php
src/views/radio.php
src/views/repeated.php
src/views/select.php
src/views/static.php
src/views/text.php
src/views/textarea.php

This PR may help to who wants to use helper_block.php and errors.php while creating custom inputs.

Added helperBlockPath() instead of hardcoded helper_block path

---

src/Kris/LaravelFormBuilder/Fields/FormField.php

Use same behaviour for rules as in Laravel Validator
Issue: https://github.com/kristijanhusak/laravel-form-builder/issues/614

Fix Regex/Array Rules normalisation

---

composer.json

I bumped the composer laravel dependency to allow laravel 8. 
No breaking changes were expected.

updated dependency support for laravel 8

---

src/Kris/LaravelFormBuilder/Fields/FormField.php

Fix choice render, #636

---

src/Kris/LaravelFormBuilder/Fields/FormField.php
src/config/config.php

To change the default from `p` to `div`, but still allow customization per field.

config option help_block_tag

---

src/Kris/LaravelFormBuilder/Fields/ChoiceType.php

Fixed `ChoiceType::determineChoiceField` so that  it always returns the `choiceType`.

Fixed the return of `ChoiceType::determineChoiceField`.

---

src/Kris/LaravelFormBuilder/Fields/FormField.php
src/Kris/LaravelFormBuilder/FormHelper.php
tests/FormHelperTest.php

Getting field type by class name that is like Symfony.
```php
$form->add('name', EmailType::class);
```
```php
class EmailType extends InputType
{
public function getType()
{
return 'email';
}
}
```

Getting field type by class name

---

tests/Fields/ButtonGroupTypeTest.php
tests/Fields/CheckableTypeTest.php
tests/Fields/SelectTypeTest.php
tests/Fields/TextareaTypeTest.php

Added tests for fields
- ButtonGroupType
- CheckableType
- SelectType
- TextareaType

Added tests for fields without tests

---

src/Kris/LaravelFormBuilder/Fields/CollectionType.php

If there's no original data, only `empty_row` data should be used, so only 1 row, AND formatted into models if `empty_model` is set.

collection input using empty_model

---

src/Kris/LaravelFormBuilder/FormBuilderServiceProvider.php
tests/FormBuilderTestCase.php

This project doesn't support laravelcollective/html less than 5.4. 
https://github.com/kristijanhusak/laravel-form-builder/blob/ad01f1cf8eb2dd953fc4d4c9d3fa51d703d61723/composer.json#L14

Drop Laravel less than 5.4

---

src/Kris/LaravelFormBuilder/Rules.php

Refactored the `Rules` class. I didn't add type hints to avoid losing compatibility.

Refactored the `Rules` Class

---

src/Kris/LaravelFormBuilder/Fields/ChildFormType.php

 use specific language_name in a ChildForm Collection #728

---

.github/workflows/test.yml
composer.json

Add support for Laravel 12
